name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: testing nizapizza.com server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: nizapizza.com
          username: nizar
          key: ${{ secrets.PIZZABOX_SSH }}
          port: 22
          script: |
            cd software/covdash
            kill $( ps aux | grep python | grep flask | awk '{print $2}' )
            git pull
            nohup python3 -m flask run &
